"""The skill-writer agent: studies a company's corpus and WRITES the agent
skill brief (agent/skills/<company>.md) that the Reader agents run on.

run_skill_writer(company) launches a tool-use agent with the same corpus tools
as the Reader (search_corpus + read_doc) plus a terminal submit_skill tool.
Its job: map the corpus, locate where every target metric is reported, capture
the latest guidance with doc paths + dates, list traps, and produce the
driver-key task list — preserving every driver key from
research/drivers/<company>.json so the pipeline contract holds.

On submit_skill the markdown is written to agent/skills/<company>.md (previous
file backed up to .bak) with a generated-by header comment.

CLI: .venv/bin/python -m agent.skillgen <company>
Trace: logs/agent-trace-skillgen-<company>-<ts>.jsonl
"""
import json
import shutil
import sys
from datetime import datetime, timezone

import anthropic
from anthropic import beta_tool

from agent import tools
from agent.loop import MAX_ITERATIONS, ROOT, SKILLS, _load_env, load_config

COMPANIES = ("hays", "home-depot", "analog-devices", "deere")

SYSTEM_TEMPLATE = """You are the skill-writer agent for an offline financial-forecasting pipeline.

Your task: study the frozen document corpus for {company} (under
challenge/offline-data/{company}/ — start with INDEX.md, then the latest
guidance documents and the historical reporting cadence) and WRITE a complete
agent skill brief that a Reader agent will use to extract forecast drivers.

Use search_corpus and read_doc to ground every claim in real documents. Do not
invent paths or quotes — verify each doc path you cite by reading it.

The brief MUST be a single markdown document with these sections:

## Corpus map
What document types exist, naming conventions, date ranges, which docs matter.

## Where each target metric is reported
For each metric the pipeline forecasts, the exact doc paths (repo-relative,
e.g. challenge/offline-data/{company}/filings/...) where it is reported, and
what the line items look like.

## Latest guidance
The most recent management guidance relevant to the forecast: doc paths,
publication dates, and the guided figures/ranges verbatim.

## Traps and pitfalls
Restatements, one-offs, tariff/FX effects, changed segment definitions,
adjusted-vs-GAAP confusion, fiscal-calendar quirks — anything that could make
a naive extraction wrong.

## Driver task list
One task per driver key. You MUST include every one of these driver keys —
this is the pipeline contract and the keys may not be renamed or dropped:

{driver_keys}

For each key: what to extract, where to look (doc paths), the expected unit,
and how to verify the value against the corpus.

When the brief is complete, call submit_skill exactly once with the full
markdown. Keep it dense and factual — it is operating instructions for another
agent, not prose for humans."""


def _driver_keys(company: str) -> list[str]:
    """Every driver key from the pinned drivers file — the pipeline contract."""
    p = ROOT / "research" / "drivers" / f"{company}.json"
    try:
        data = json.loads(p.read_text())
        return list((data.get("drivers") or {}).keys())
    except (OSError, json.JSONDecodeError):
        return []


def run_skill_writer(company: str) -> str | None:
    """One skill-writer pass. Returns the written skill path, or None on failure."""
    if company not in COMPANIES:
        raise ValueError(f"unknown company '{company}' (expected one of {COMPANIES})")

    _load_env()
    cfg = load_config()
    client = anthropic.Anthropic()

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    logdir = ROOT / "logs"
    logdir.mkdir(exist_ok=True)
    trace_path = logdir / f"agent-trace-skillgen-{company}-{stamp}.jsonl"
    tools.set_trace(trace_path)

    skill_path = SKILLS / f"{company}.md"
    written: dict = {"path": None}

    @beta_tool
    def submit_skill(markdown: str) -> str:
        """Submit the finished agent skill brief as a complete markdown
        document. Call exactly once, when every required section (corpus map,
        metric locations, latest guidance, traps, driver task list with every
        driver key) is present.

        Args:
            markdown: The full markdown content of the skill brief.
        """
        if not markdown or not markdown.strip():
            return "ERROR: empty markdown — write the full brief and resubmit"
        missing = [k for k in _driver_keys(company) if k not in markdown]
        if missing:
            return ("ERROR: brief is missing driver keys: "
                    + ", ".join(missing) + " — include every key and resubmit")
        header = (f"<!-- generated by skill-writer agent "
                  f"{datetime.now(timezone.utc).isoformat()} -->\n")
        if skill_path.exists():
            shutil.copy2(skill_path, skill_path.with_suffix(".md.bak"))
        skill_path.write_text(header + markdown.strip() + "\n")
        written["path"] = str(skill_path.relative_to(ROOT))
        return f"written: {written['path']} ({len(markdown)} chars)"

    keys = _driver_keys(company)
    system = SYSTEM_TEMPLATE.format(
        company=company,
        driver_keys="\n".join(f"- {k}" for k in keys) if keys else "(no pinned drivers file found — derive sensible keys from the corpus)",
    )

    runner = client.beta.messages.tool_runner(
        model=cfg["model"],
        max_tokens=32000,
        output_config={"effort": cfg["effort"]},
        system=system,
        tools=[tools.search_corpus, tools.read_doc, submit_skill],
        messages=[{"role": "user", "content":
                   f"Study the {company} corpus and write the skill brief. "
                   f"Verify every doc path you cite, then call submit_skill once."}],
        max_iterations=MAX_ITERATIONS,
    )

    last_message = None
    for message in runner:
        last_message = message
        if message.stop_reason == "refusal":
            print(f"[skillgen {company}] refusal — aborting")
            return None

    if last_message is not None and getattr(last_message, "stop_reason", None) == "pause_turn":
        print(f"[skillgen {company}] ended on pause_turn — partial run, nothing may have been written")

    if written["path"] is None:
        print(f"[skillgen {company}] finished without a valid submit_skill call")
        return None
    print(f"[skillgen {company}] wrote {written['path']} (trace: {trace_path.relative_to(ROOT)})")
    return written["path"]


def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] not in COMPANIES:
        print(f"usage: python -m agent.skillgen <{'|'.join(COMPANIES)}>")
        return 2
    return 0 if run_skill_writer(sys.argv[1]) else 1


if __name__ == "__main__":
    raise SystemExit(main())
